- name: Make sure git is installed
  tags: git
  apt: name=git state=present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Make sure unzip is installed
  tags: unzip
  apt: name=unzip state=present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

